_BASE_: "../../../Base-RCNN-DilatedC5.yaml"
MODEL:
  META_ARCHITECTURE: "SemanticSegmentor"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_deeplab_backbone"    #  build_resnet_backbone
  RESNETS:
    RES4_DILATION: 1
    RES5_DILATION: 2
    OUT_FEATURES: [ "res2", "res5" ]
    RES5_MULTI_GRID: [ 1, 2, 4 ]
    STEM_TYPE: "deeplab"
    STEM_OUT_CHANNELS: 64
  SEM_SEG_HEAD:
    NAME: "DeepLabV3PlusHead"    # DeepLabV3Head
    IN_FEATURES: ["res2", "res5"]
    PROJECT_FEATURES: [ "res2" ]
    PROJECT_CHANNELS: [ 48 ]
    NORM: "SyncBN"
#    NORM: "BN"
    ASPP_CHANNELS: 256
    ASPP_DILATIONS: [6, 12, 18]
    ASPP_DROPOUT: 0.1
    CONVS_DIM: 256
    COMMON_STRIDE: 4
    NUM_CLASSES: 19
    LOSS_TYPE: "hard_pixel_mining"
    IGNORE_VALUE: 255
DATASETS:
  TRAIN: ("cityscapes_fine_sem_seg_train",)
  TEST: ("cityscapes_fine_sem_seg_val",)
SOLVER:
  CHECKPOINT_PERIOD: 5000
  BASE_LR: 0.01
#  MAX_ITER: 90000
  MAX_ITER: 180000
  LR_SCHEDULER_NAME: "WarmupPolyLR"
#  IMS_PER_BATCH: 16
  IMS_PER_BATCH: 8
  CLIP_GRADIENTS:
    ENABLED: False
  STEPS: (120000, 160000)
INPUT:
  MIN_SIZE_TRAIN: (512, 768, 1024, 1280, 1536, 1792, 2048)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 4096
  MAX_SIZE_TEST: 2048
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (512, 1024)
#    SIZE: (256, 512)
    SINGLE_CATEGORY_MAX_AREA: 1.0
DATALOADER:
  NUM_WORKERS: 8
TEST:
  EVAL_PERIOD: 0

OUTPUT_DIR: '/home/ljm/Fdisk_A/train_outputs/train_output_seg/seg101/searched_model_seg101_cityscapes/cityscapes_deeplabv3_plus/'
SEED: '2223'